version: "3"
services:
  web:
	# replace username/repo:tag with your name and image details
    image: lux563624348/epgg:customized
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "4.0"
          memory: 4000M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet:
